// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/mats0319/unnamed_plan/server/internal/db/model"
)

func newCloudFile(db *gorm.DB, opts ...gen.DOOption) cloudFile {
	_cloudFile := cloudFile{}

	_cloudFile.cloudFileDo.UseDB(db, opts...)
	_cloudFile.cloudFileDo.UseModel(&model.CloudFile{})

	tableName := _cloudFile.cloudFileDo.TableName()
	_cloudFile.ALL = field.NewAsterisk(tableName)
	_cloudFile.ID = field.NewUint(tableName, "id")
	_cloudFile.CreatedAt = field.NewInt64(tableName, "created_at")
	_cloudFile.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_cloudFile.DeletedAt = field.NewField(tableName, "deleted_at")
	_cloudFile.FileID = field.NewString(tableName, "file_id")
	_cloudFile.Name = field.NewString(tableName, "name")
	_cloudFile.Extension = field.NewString(tableName, "extension")
	_cloudFile.Uploader = field.NewUint(tableName, "uploader")
	_cloudFile.Size = field.NewInt64(tableName, "size")
	_cloudFile.Hash = field.NewString(tableName, "hash")
	_cloudFile.IsDeleted = field.NewBool(tableName, "is_deleted")

	_cloudFile.fillFieldMap()

	return _cloudFile
}

type cloudFile struct {
	cloudFileDo cloudFileDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Int64
	UpdatedAt field.Int64
	DeletedAt field.Field
	FileID    field.String
	Name      field.String
	Extension field.String
	Uploader  field.Uint
	Size      field.Int64
	Hash      field.String
	IsDeleted field.Bool

	fieldMap map[string]field.Expr
}

func (c cloudFile) Table(newTableName string) *cloudFile {
	c.cloudFileDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cloudFile) As(alias string) *cloudFile {
	c.cloudFileDo.DO = *(c.cloudFileDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cloudFile) updateTableName(table string) *cloudFile {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.CreatedAt = field.NewInt64(table, "created_at")
	c.UpdatedAt = field.NewInt64(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.FileID = field.NewString(table, "file_id")
	c.Name = field.NewString(table, "name")
	c.Extension = field.NewString(table, "extension")
	c.Uploader = field.NewUint(table, "uploader")
	c.Size = field.NewInt64(table, "size")
	c.Hash = field.NewString(table, "hash")
	c.IsDeleted = field.NewBool(table, "is_deleted")

	c.fillFieldMap()

	return c
}

func (c *cloudFile) WithContext(ctx context.Context) ICloudFileDo {
	return c.cloudFileDo.WithContext(ctx)
}

func (c cloudFile) TableName() string { return c.cloudFileDo.TableName() }

func (c cloudFile) Alias() string { return c.cloudFileDo.Alias() }

func (c cloudFile) Columns(cols ...field.Expr) gen.Columns { return c.cloudFileDo.Columns(cols...) }

func (c *cloudFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cloudFile) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["file_id"] = c.FileID
	c.fieldMap["name"] = c.Name
	c.fieldMap["extension"] = c.Extension
	c.fieldMap["uploader"] = c.Uploader
	c.fieldMap["size"] = c.Size
	c.fieldMap["hash"] = c.Hash
	c.fieldMap["is_deleted"] = c.IsDeleted
}

func (c cloudFile) clone(db *gorm.DB) cloudFile {
	c.cloudFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cloudFile) replaceDB(db *gorm.DB) cloudFile {
	c.cloudFileDo.ReplaceDB(db)
	return c
}

type cloudFileDo struct{ gen.DO }

type ICloudFileDo interface {
	gen.SubQuery
	Debug() ICloudFileDo
	WithContext(ctx context.Context) ICloudFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICloudFileDo
	WriteDB() ICloudFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICloudFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICloudFileDo
	Not(conds ...gen.Condition) ICloudFileDo
	Or(conds ...gen.Condition) ICloudFileDo
	Select(conds ...field.Expr) ICloudFileDo
	Where(conds ...gen.Condition) ICloudFileDo
	Order(conds ...field.Expr) ICloudFileDo
	Distinct(cols ...field.Expr) ICloudFileDo
	Omit(cols ...field.Expr) ICloudFileDo
	Join(table schema.Tabler, on ...field.Expr) ICloudFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICloudFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICloudFileDo
	Group(cols ...field.Expr) ICloudFileDo
	Having(conds ...gen.Condition) ICloudFileDo
	Limit(limit int) ICloudFileDo
	Offset(offset int) ICloudFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICloudFileDo
	Unscoped() ICloudFileDo
	Create(values ...*model.CloudFile) error
	CreateInBatches(values []*model.CloudFile, batchSize int) error
	Save(values ...*model.CloudFile) error
	First() (*model.CloudFile, error)
	Take() (*model.CloudFile, error)
	Last() (*model.CloudFile, error)
	Find() ([]*model.CloudFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CloudFile, err error)
	FindInBatches(result *[]*model.CloudFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CloudFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICloudFileDo
	Assign(attrs ...field.AssignExpr) ICloudFileDo
	Joins(fields ...field.RelationField) ICloudFileDo
	Preload(fields ...field.RelationField) ICloudFileDo
	FirstOrInit() (*model.CloudFile, error)
	FirstOrCreate() (*model.CloudFile, error)
	FindByPage(offset int, limit int) (result []*model.CloudFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICloudFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cloudFileDo) Debug() ICloudFileDo {
	return c.withDO(c.DO.Debug())
}

func (c cloudFileDo) WithContext(ctx context.Context) ICloudFileDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cloudFileDo) ReadDB() ICloudFileDo {
	return c.Clauses(dbresolver.Read)
}

func (c cloudFileDo) WriteDB() ICloudFileDo {
	return c.Clauses(dbresolver.Write)
}

func (c cloudFileDo) Session(config *gorm.Session) ICloudFileDo {
	return c.withDO(c.DO.Session(config))
}

func (c cloudFileDo) Clauses(conds ...clause.Expression) ICloudFileDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cloudFileDo) Returning(value interface{}, columns ...string) ICloudFileDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cloudFileDo) Not(conds ...gen.Condition) ICloudFileDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cloudFileDo) Or(conds ...gen.Condition) ICloudFileDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cloudFileDo) Select(conds ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cloudFileDo) Where(conds ...gen.Condition) ICloudFileDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cloudFileDo) Order(conds ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cloudFileDo) Distinct(cols ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cloudFileDo) Omit(cols ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cloudFileDo) Join(table schema.Tabler, on ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cloudFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cloudFileDo) RightJoin(table schema.Tabler, on ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cloudFileDo) Group(cols ...field.Expr) ICloudFileDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cloudFileDo) Having(conds ...gen.Condition) ICloudFileDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cloudFileDo) Limit(limit int) ICloudFileDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cloudFileDo) Offset(offset int) ICloudFileDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cloudFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICloudFileDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cloudFileDo) Unscoped() ICloudFileDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cloudFileDo) Create(values ...*model.CloudFile) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cloudFileDo) CreateInBatches(values []*model.CloudFile, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cloudFileDo) Save(values ...*model.CloudFile) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cloudFileDo) First() (*model.CloudFile, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CloudFile), nil
	}
}

func (c cloudFileDo) Take() (*model.CloudFile, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CloudFile), nil
	}
}

func (c cloudFileDo) Last() (*model.CloudFile, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CloudFile), nil
	}
}

func (c cloudFileDo) Find() ([]*model.CloudFile, error) {
	result, err := c.DO.Find()
	return result.([]*model.CloudFile), err
}

func (c cloudFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CloudFile, err error) {
	buf := make([]*model.CloudFile, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cloudFileDo) FindInBatches(result *[]*model.CloudFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cloudFileDo) Attrs(attrs ...field.AssignExpr) ICloudFileDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cloudFileDo) Assign(attrs ...field.AssignExpr) ICloudFileDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cloudFileDo) Joins(fields ...field.RelationField) ICloudFileDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cloudFileDo) Preload(fields ...field.RelationField) ICloudFileDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cloudFileDo) FirstOrInit() (*model.CloudFile, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CloudFile), nil
	}
}

func (c cloudFileDo) FirstOrCreate() (*model.CloudFile, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CloudFile), nil
	}
}

func (c cloudFileDo) FindByPage(offset int, limit int) (result []*model.CloudFile, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cloudFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cloudFileDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cloudFileDo) Delete(models ...*model.CloudFile) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cloudFileDo) withDO(do gen.Dao) *cloudFileDo {
	c.DO = *do.(*gen.DO)
	return c
}
