// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"github.com/mats0319/unnamed_plan/server/internal/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newFlipGameScore(db *gorm.DB, opts ...gen.DOOption) flipGameScore {
	_flipGameScore := flipGameScore{}

	_flipGameScore.flipGameScoreDo.UseDB(db, opts...)
	_flipGameScore.flipGameScoreDo.UseModel(&model.FlipGameScore{})

	tableName := _flipGameScore.flipGameScoreDo.TableName()
	_flipGameScore.ALL = field.NewAsterisk(tableName)
	_flipGameScore.ID = field.NewField(tableName, "id")
	_flipGameScore.CreatedAt = field.NewInt64(tableName, "created_at")
	_flipGameScore.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_flipGameScore.DeletedAt = field.NewField(tableName, "deleted_at")
	_flipGameScore.BackupAt = field.NewInt64(tableName, "backup_at")
	_flipGameScore.Score = field.NewInt(tableName, "score")
	_flipGameScore.Result = field.NewString(tableName, "result")
	_flipGameScore.Player = field.NewString(tableName, "player")
	_flipGameScore.PlayerName = field.NewString(tableName, "player_name")

	_flipGameScore.fillFieldMap()

	return _flipGameScore
}

type flipGameScore struct {
	flipGameScoreDo flipGameScoreDo

	ALL        field.Asterisk
	ID         field.Field
	CreatedAt  field.Int64
	UpdatedAt  field.Int64
	DeletedAt  field.Field
	BackupAt   field.Int64
	Score      field.Int
	Result     field.String
	Player     field.String
	PlayerName field.String

	fieldMap map[string]field.Expr
}

func (f flipGameScore) Table(newTableName string) *flipGameScore {
	f.flipGameScoreDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f flipGameScore) As(alias string) *flipGameScore {
	f.flipGameScoreDo.DO = *(f.flipGameScoreDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *flipGameScore) updateTableName(table string) *flipGameScore {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewField(table, "id")
	f.CreatedAt = field.NewInt64(table, "created_at")
	f.UpdatedAt = field.NewInt64(table, "updated_at")
	f.DeletedAt = field.NewField(table, "deleted_at")
	f.BackupAt = field.NewInt64(table, "backup_at")
	f.Score = field.NewInt(table, "score")
	f.Result = field.NewString(table, "result")
	f.Player = field.NewString(table, "player")
	f.PlayerName = field.NewString(table, "player_name")

	f.fillFieldMap()

	return f
}

func (f *flipGameScore) WithContext(ctx context.Context) IFlipGameScoreDo {
	return f.flipGameScoreDo.WithContext(ctx)
}

func (f flipGameScore) TableName() string { return f.flipGameScoreDo.TableName() }

func (f flipGameScore) Alias() string { return f.flipGameScoreDo.Alias() }

func (f flipGameScore) Columns(cols ...field.Expr) gen.Columns {
	return f.flipGameScoreDo.Columns(cols...)
}

func (f *flipGameScore) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *flipGameScore) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 9)
	f.fieldMap["id"] = f.ID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
	f.fieldMap["backup_at"] = f.BackupAt
	f.fieldMap["score"] = f.Score
	f.fieldMap["result"] = f.Result
	f.fieldMap["player"] = f.Player
	f.fieldMap["player_name"] = f.PlayerName
}

func (f flipGameScore) clone(db *gorm.DB) flipGameScore {
	f.flipGameScoreDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f flipGameScore) replaceDB(db *gorm.DB) flipGameScore {
	f.flipGameScoreDo.ReplaceDB(db)
	return f
}

type flipGameScoreDo struct{ gen.DO }

type IFlipGameScoreDo interface {
	gen.SubQuery
	Debug() IFlipGameScoreDo
	WithContext(ctx context.Context) IFlipGameScoreDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFlipGameScoreDo
	WriteDB() IFlipGameScoreDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFlipGameScoreDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFlipGameScoreDo
	Not(conds ...gen.Condition) IFlipGameScoreDo
	Or(conds ...gen.Condition) IFlipGameScoreDo
	Select(conds ...field.Expr) IFlipGameScoreDo
	Where(conds ...gen.Condition) IFlipGameScoreDo
	Order(conds ...field.Expr) IFlipGameScoreDo
	Distinct(cols ...field.Expr) IFlipGameScoreDo
	Omit(cols ...field.Expr) IFlipGameScoreDo
	Join(table schema.Tabler, on ...field.Expr) IFlipGameScoreDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFlipGameScoreDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFlipGameScoreDo
	Group(cols ...field.Expr) IFlipGameScoreDo
	Having(conds ...gen.Condition) IFlipGameScoreDo
	Limit(limit int) IFlipGameScoreDo
	Offset(offset int) IFlipGameScoreDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFlipGameScoreDo
	Unscoped() IFlipGameScoreDo
	Create(values ...*model.FlipGameScore) error
	CreateInBatches(values []*model.FlipGameScore, batchSize int) error
	Save(values ...*model.FlipGameScore) error
	First() (*model.FlipGameScore, error)
	Take() (*model.FlipGameScore, error)
	Last() (*model.FlipGameScore, error)
	Find() ([]*model.FlipGameScore, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FlipGameScore, err error)
	FindInBatches(result *[]*model.FlipGameScore, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FlipGameScore) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFlipGameScoreDo
	Assign(attrs ...field.AssignExpr) IFlipGameScoreDo
	Joins(fields ...field.RelationField) IFlipGameScoreDo
	Preload(fields ...field.RelationField) IFlipGameScoreDo
	FirstOrInit() (*model.FlipGameScore, error)
	FirstOrCreate() (*model.FlipGameScore, error)
	FindByPage(offset int, limit int) (result []*model.FlipGameScore, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFlipGameScoreDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f flipGameScoreDo) Debug() IFlipGameScoreDo {
	return f.withDO(f.DO.Debug())
}

func (f flipGameScoreDo) WithContext(ctx context.Context) IFlipGameScoreDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f flipGameScoreDo) ReadDB() IFlipGameScoreDo {
	return f.Clauses(dbresolver.Read)
}

func (f flipGameScoreDo) WriteDB() IFlipGameScoreDo {
	return f.Clauses(dbresolver.Write)
}

func (f flipGameScoreDo) Session(config *gorm.Session) IFlipGameScoreDo {
	return f.withDO(f.DO.Session(config))
}

func (f flipGameScoreDo) Clauses(conds ...clause.Expression) IFlipGameScoreDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f flipGameScoreDo) Returning(value interface{}, columns ...string) IFlipGameScoreDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f flipGameScoreDo) Not(conds ...gen.Condition) IFlipGameScoreDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f flipGameScoreDo) Or(conds ...gen.Condition) IFlipGameScoreDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f flipGameScoreDo) Select(conds ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f flipGameScoreDo) Where(conds ...gen.Condition) IFlipGameScoreDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f flipGameScoreDo) Order(conds ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f flipGameScoreDo) Distinct(cols ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f flipGameScoreDo) Omit(cols ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f flipGameScoreDo) Join(table schema.Tabler, on ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f flipGameScoreDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f flipGameScoreDo) RightJoin(table schema.Tabler, on ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f flipGameScoreDo) Group(cols ...field.Expr) IFlipGameScoreDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f flipGameScoreDo) Having(conds ...gen.Condition) IFlipGameScoreDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f flipGameScoreDo) Limit(limit int) IFlipGameScoreDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f flipGameScoreDo) Offset(offset int) IFlipGameScoreDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f flipGameScoreDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFlipGameScoreDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f flipGameScoreDo) Unscoped() IFlipGameScoreDo {
	return f.withDO(f.DO.Unscoped())
}

func (f flipGameScoreDo) Create(values ...*model.FlipGameScore) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f flipGameScoreDo) CreateInBatches(values []*model.FlipGameScore, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f flipGameScoreDo) Save(values ...*model.FlipGameScore) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f flipGameScoreDo) First() (*model.FlipGameScore, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlipGameScore), nil
	}
}

func (f flipGameScoreDo) Take() (*model.FlipGameScore, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlipGameScore), nil
	}
}

func (f flipGameScoreDo) Last() (*model.FlipGameScore, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlipGameScore), nil
	}
}

func (f flipGameScoreDo) Find() ([]*model.FlipGameScore, error) {
	result, err := f.DO.Find()
	return result.([]*model.FlipGameScore), err
}

func (f flipGameScoreDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FlipGameScore, err error) {
	buf := make([]*model.FlipGameScore, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f flipGameScoreDo) FindInBatches(result *[]*model.FlipGameScore, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f flipGameScoreDo) Attrs(attrs ...field.AssignExpr) IFlipGameScoreDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f flipGameScoreDo) Assign(attrs ...field.AssignExpr) IFlipGameScoreDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f flipGameScoreDo) Joins(fields ...field.RelationField) IFlipGameScoreDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f flipGameScoreDo) Preload(fields ...field.RelationField) IFlipGameScoreDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f flipGameScoreDo) FirstOrInit() (*model.FlipGameScore, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlipGameScore), nil
	}
}

func (f flipGameScoreDo) FirstOrCreate() (*model.FlipGameScore, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlipGameScore), nil
	}
}

func (f flipGameScoreDo) FindByPage(offset int, limit int) (result []*model.FlipGameScore, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f flipGameScoreDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f flipGameScoreDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f flipGameScoreDo) Delete(models ...*model.FlipGameScore) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *flipGameScoreDo) withDO(do gen.Dao) *flipGameScoreDo {
	f.DO = *do.(*gen.DO)
	return f
}
